"""
Romih Agent - Draw Tool (SVG & ASCII)
======================================
أداة رسم بسيطة - توليد SVG و ASCII art
"""
import os, re, json, base64
from dataclasses import dataclass

@dataclass
class DrawTool:
    """أداة الرسم - توليد رسوم SVG و ASCII"""
    name: str = "draw"
    description: str = "رسم تخطيطات ورسوم بيانية بسيطة (SVG/ASCII)"
    category: str = "creative"
    risk: str = "low"

    def execute(self, description: str = "", style: str = "svg") -> str:
        """
        توليد رسم بناءً على الوصف
        
        Args:
            description: وصف للرسم المطلوب
            style: svg (رسم متجه) أو ascii (رسم نصي)
        """
        if style == "ascii":
            return self._generate_ascii(description)
        return self._generate_svg(description)

    def _generate_svg(self, description: str) -> str:
        """توليد SVG بسيط"""
        # SVG template with Arabic labels
        svg = f"""<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 600 400" width="100%" style="max-width:600px;background:#1a1a2e;border-radius:12px">
  <defs>
    <marker id="arrow" markerWidth="10" markerHeight="7" refX="9" refY="3.5" orient="auto">
      <polygon points="0 0, 10 3.5, 0 7" fill="#a78bfa"/>
    </marker>
  </defs>
  <style>
    text {{ font-family: system-ui, sans-serif; fill: #e2e8f0; font-size: 13px; text-anchor: middle; }}
    .title {{ font-size: 18px; font-weight: bold; fill: #a78bfa; }}
    .label {{ font-size: 11px; fill: #94a3b8; }}
    .en {{ font-size: 10px; fill: #64748b; }}
  </style>
  <!-- Title -->
  <text x="300" y="30" class="title">{description[:60]}</text>
  <!-- Generated by Romih Agent -->
  <text x="300" y="380" class="label">Romih Agent • {description[:40]}</text>
</svg>"""
        return f"```svg\n{svg}\n```"

    def _generate_ascii(self, description: str) -> str:
        """توليد ASCII art بسيط"""
        art = f"""    +----------------------------------+
    |     {description[:30]:^30} |
    +----------------------------------+
    |  Romih Agent • رسم تخطيطي بسيط  |
    +----------------------------------+"""
        return art

    def get_tool_prompt(self) -> str:
        return """يمكنك رسم تخطيطات بسيطة عبر SVG أو ASCII art. استخدم:
- رسم SVG: اكتب كود SVG كامل داخل ```svg ... ``` - يظهر في المتصفح
- رسم ASCII: استخدم ```ascii ... ``` - رسم نصي بسيط"""
