"""
Romih Power Tools - PDF, Excel, Charts, Web Search, YouTube
===========================================================
Lightweight: uses only built-in Python + lightweight deps
"""
import os, json, io, csv, tempfile, re

def register(tools_registry):
    """Register all power tools"""

    # === 1. PDF GENERATION (pure Python HTML→PDF approach) ===
    def generate_pdf(params):
        """Generate a PDF report via HTML. Returns HTML that can be printed as PDF."""
        title = params.get('title', 'Report')
        content = params.get('content', 'No content')
        
        # Escape Arabic for HTML
        def ae(s):
            return ''.join(f'&#{ord(c)};' if ord(c) > 127 else c for c in s)
        
        html = f"""<!DOCTYPE html><html dir="rtl"><head><meta charset="UTF-8">
<style>body{{font-family:Arial,sans-serif;max-width:800px;margin:40px auto;padding:20px;line-height:1.8;color:#1a1a2e}}
h1{{color:#2563eb;text-align:center;border-bottom:3px solid #2563eb;padding-bottom:10px}}
h2{{color:#7c3aed;margin-top:30px}}
.footer{{text-align:center;margin-top:40px;color:#888;font-size:12px;border-top:1px solid #ddd;padding-top:10px}}
</style></head><body>
<h1>{ae(title)}</h1>
{ae(content)}
<div class="footer">Generated by Romih Agent | وكيلك الذكي</div>
</body></html>"""
        
        path = os.path.join(tempfile.gettempdir(), 'romih_report.html')
        with open(path, 'w', encoding='utf-8') as f:
            f.write(html)
        return json.dumps({
            "status": "ok", "file": path, "format": "html",
            "message": "Report generated as HTML. Open in browser and Print→Save as PDF."
        }, ensure_ascii=False)

    tools_registry.register(tools_registry.Tool(
        name="generate_pdf", description="Generate a professional report as HTML (printable to PDF). Arabic supported.",
        parameters={"title": "Title", "content": "Content"},
        func=generate_pdf, category="power"
    ))

    # === 2. EXCEL/CSV GENERATION ===
    def generate_excel(params):
        """Generate CSV data (Excel-compatible)."""
        headers = params.get('headers', ['Column1', 'Column2'])
        rows = params.get('rows', [])
        filename = params.get('filename', 'data')
        
        csv_path = os.path.join(tempfile.gettempdir(), f'{filename}.csv')
        with open(csv_path, 'w', encoding='utf-8-sig', newline='') as f:
            w = csv.writer(f)
            w.writerow(headers)
            for row in rows:
                w.writerow(row)
        
        # Also create HTML table for Telegram display
        html = '<table border="1" style="border-collapse:collapse">'
        html += '<tr>' + ''.join(f'<th style="padding:8px;background:#2563eb;color:white">{h}</th>' for h in headers) + '</tr>'
        for row in rows[:20]:
            html += '<tr>' + ''.join(f'<td style="padding:6px">{c}</td>' for c in row) + '</tr>'
        html += '</table>'
        
        return json.dumps({
            "status": "ok", "file": csv_path, "rows": len(rows),
            "table_html": html,
            "message": f"Data saved as CSV ({len(rows)} rows). Opens in Excel directly."
        }, ensure_ascii=False)

    tools_registry.register(tools_registry.Tool(
        name="generate_excel", description="Generate CSV data (opens in Excel). With HTML table for display.",
        parameters={"headers": "Column headers (list)", "rows": "Data rows (list of lists)", "filename": "Optional name"},
        func=generate_excel, category="power"
    ))

    # === 3. CHART DATA GENERATION ===
    def generate_chart(params):
        """Generate chart data + ASCII view. Returns structured data for rendering."""
        chart_type = params.get('type', 'bar')
        title = params.get('title', 'Chart')
        labels = params.get('labels', ['A', 'B', 'C'])
        values = params.get('values', [10, 20, 30])
        
        # Simple ASCII bar chart
        max_val = max(values) if values else 1
        ascii_chart = f"\n📊 {title}\n\n"
        for i, (label, val) in enumerate(zip(labels, values)):
            bar_len = int((val / max_val) * 30)
            bar = '█' * bar_len
            ascii_chart += f"  {label:15s} |{bar} {val}\n"
        
        return json.dumps({
            "status": "ok", "type": chart_type, "title": title,
            "labels": labels, "values": values,
            "ascii": ascii_chart,
            "message": f"Chart data ready. Use with any charting library."
        }, ensure_ascii=False)

    tools_registry.register(tools_registry.Tool(
        name="generate_chart", description="Generate chart data with ASCII visualization",
        parameters={"type": "bar/line/pie", "title": "Title", "labels": "Labels", "values": "Values"},
        func=generate_chart, category="power"
    ))

    # === 4. WEB SEARCH ===
    def web_search(params):
        """Search web and return results."""
        query = params.get('query', '')
        num = int(params.get('num_results', 5))
        
        try:
            import urllib.request, urllib.parse
            url = f"https://www.google.com/search?q={urllib.parse.quote(query)}&num={num}"
            req = urllib.request.Request(url, headers={'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)'})
            data = urllib.request.urlopen(req, timeout=10).read().decode('utf-8', errors='ignore')
            
            results = []
            titles = re.findall(r'<h3[^>]*>(.*?)</h3>', data)
            snippets = re.findall(r'<div class="BNeawe s3v9rd[^"]*">(.*?)</div>', data)
            
            for i in range(min(num, len(titles))):
                title = re.sub(r'<[^>]+>', '', titles[i])
                snippet = re.sub(r'<[^>]+>', '', snippets[i]) if i < len(snippets) else ''
                results.append({"title": title, "snippet": snippet[:200]})
            
            return json.dumps({"query": query, "results": results, "count": len(results)}, ensure_ascii=False)
        except Exception as e:
            return json.dumps({"error": str(e), "query": query}, ensure_ascii=False)

    tools_registry.register(tools_registry.Tool(
        name="web_search", description="Search the web and return results",
        parameters={"query": "Search query", "num_results": "Count (default 5)"},
        func=web_search, category="power"
    ))

    # === 5. YOUTUBE TRANSCRIPT ===
    def youtube_transcript(params):
        """Get transcript from YouTube video."""
        url = params.get('url', '')
        try:
            import subprocess
            result = subprocess.run([
                'yt-dlp', '--skip-download', '--write-auto-subs',
                '--sub-lang', 'ar,en', '--convert-subs', 'srt',
                '--output', os.path.join(tempfile.gettempdir(), '%(id)s'), 
                url
            ], capture_output=True, text=True, timeout=60)
            
            import glob
            vid_id = re.search(r'v=([^&]+)', url)
            if vid_id:
                vid_id = vid_id.group(1)
                subs = glob.glob(os.path.join(tempfile.gettempdir(), f'{vid_id}*.srt'))
                if subs:
                    with open(subs[0], 'r', encoding='utf-8', errors='ignore') as f:
                        text = f.read()
                    os.unlink(subs[0])
                    text = re.sub(r'\d+\n\d{2}:\d{2}:\d{2}[.,]\d{3} -->.*\n', '', text)
                    text = re.sub(r'<[^>]+>', '', text).strip()
                    return json.dumps({"status": "ok", "transcript": text[:5000], "length": len(text)}, ensure_ascii=False)
            
            return json.dumps({"status": "no_subtitles", "url": url}, ensure_ascii=False)
        except Exception as e:
            return json.dumps({"error": str(e), "url": url}, ensure_ascii=False)

    tools_registry.register(tools_registry.Tool(
        name="youtube_transcript", description="Get transcript from YouTube video",
        parameters={"url": "YouTube URL"},
        func=youtube_transcript, category="power"
    ))

    return 5
